### ISSUE TITLE
On join error

### ISSUE THREAD

**Issue by fuyutsuki** [CookieSoftware/Cookie-MP#2]
> 15:22:52 [NOTICE] Player data not found for "PlayerName", creating new profile
> 15:22:54 [CRITICAL] InvalidArgumentException: "Value -5409313646327103488 is too large!" (EXCEPTION) in "/src/pocketmine/nbt/tag/IntTag" at line 68
> 15:22:54 [NOTICE] Blocked 192.168.11.10 for 5 seconds

Server: Win10 localhost
brunch: master latest
PHP: 7.0.15

**Comment by armagadon159753** [comment]
763d68b Thank to report other beug ^•^
