### ISSUE TITLE
How can I....

### ISSUE THREAD

**Issue by jdongel2004** [CookieSoftware/Cookie-MP#3]
I want to get the .phar file. How can I do..?

**Comment by CookieCode** [comment]
You do not need a .phar! You just have to put the folder "src" in the same place as the .phar file on your FTP/SFTP. Come tell me if you have succeeded.

**Comment by jdongel2004** [comment]
Cookie-MP software is stable? @CookieCode

**Comment by CookieCode** [comment]
yes ! Afterwards, it depends to your plugins

**Comment by jdongel2004** [comment]
I see.. Please keep a commit! (Steadily)

**Comment by CookieCode** [comment]
Don't worry, I regularly post updates !

**Comment by jdongel2004** [comment]
Do you know hot to set up the CircleCI?

**Comment by CookieCode** [comment]
Nope ^•^
