### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by caspervanneck** [CookieSoftware/Cookie-MP#9]
if  i can help send me a invite

**Comment by wiligangster** [comment]
Do you have Twitter ?

**Comment by caspervanneck** [comment]
No sorry @wiligangster

**Comment by wiligangster** [comment]
If you make good commit I will put you member @caspervanneck

**Comment by CookieCode** [comment]
@caspervanneck If you make good pull requests you will be accepted into us team.
